name: Check examples
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  check_examples:
    name: Check examples output
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'adopt'
          architecture: x64
          cache: gradle

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest-stable"

      - name: Install nf-schema
        run: make install

      - name: Check examples
        run: bash examples/check_examples.sh