name: Lint code
on:
  push:
  pull_request:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run prek
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3
